apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ollama-model-viewer
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: ollama

resources:
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - deployment.yaml
  - service-ca.yaml
  - route.yaml

labels:
  - pairs:
      app.kubernetes.io/name: ollama-model-viewer
      app.kubernetes.io/component: web-viewer
      app.kubernetes.io/part-of: ollama-platform

images:
  - name: quay.io/jcollier/ollama-model-viewer
    newTag: latest

# Optional: Add configuration patches
patches: []

# Optional: Add config map or secret generators
# configMapGenerator: []
# secretGenerator: [] 