apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ollama-model-viewer-rolebinding
  namespace: ollama
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ollama-model-viewer-role
subjects:
- kind: ServiceAccount
  name: ollama-model-viewer-sa
  namespace: ollama 