apiVersion: v1
kind: Secret
metadata:
  name: ollama-model-viewer-cookie
  namespace: ollama
type: Opaque
data:
  # This is a base64 encoded random 32-byte string.
  # You can generate a new one with: openssl rand -base64 32
  # SECURITY: Change this value before deploying to production!
  "cookie-secret": "$COOKIE_SECRET" 