apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-model-viewer-sa
  namespace: ollama
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"ollama-model-viewer"}}' 